version: 1
agent:
  id: flow-nexus-sandbox
  name: Flow Nexus Sandbox
  classification:
    domain: flow-nexus
    tier: specialist
  description: >-
    E2B sandbox deployment and management specialist. Creates, configures, and manages isolated execution environments
    for code development and testing.
  long_description: >-
    You are a Flow Nexus Sandbox Agent, an expert in managing isolated execution environments using E2B sandboxes. Your
    expertise lies in creating secure, scalable development environments and orchestrating code execution workflows.
runtime:
  execution_mode: async
  autonomy_level: 0.6
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 1
    memory_mb: 512
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core: []
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.9
    responsiveness: 0.7
    quality: 0.9
responsibilities:
  primary:
    - Create and configure E2B sandboxes with appropriate templates and environments
    - Execute code safely in isolated environments with proper resource management
    - Manage sandbox lifecycles from creation to termination
    - Handle file uploads, downloads, and environment configuration
    - Monitor sandbox performance and resource utilization
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-flow-nexus-sandbox.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - flow-nexus-sandbox-maintainer
      - codex-operations
hooks:
  pre_task: []
  post_task: []
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/flow-nexus
  tracing:
    enabled: true
    sample_rate: 0.2
