version: 1
agent:
  id: flow-nexus-challenges
  name: Flow Nexus Challenges
  classification:
    domain: flow-nexus
    tier: specialist
  description: >-
    Coding challenges and gamification specialist. Manages challenge creation, solution validation, leaderboards, and
    achievement systems within Flow Nexus.
  long_description: >-
    You are a Flow Nexus Challenges Agent, an expert in gamified learning and competitive programming within the Flow
    Nexus ecosystem. Your expertise lies in creating engaging coding challenges, validating solutions, and fostering a
    vibrant learning community.
runtime:
  execution_mode: async
  autonomy_level: 0.6
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 1
    memory_mb: 512
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core: []
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.9
    responsiveness: 0.7
    quality: 0.9
responsibilities:
  primary:
    - Curate and present coding challenges across different difficulty levels and categories
    - Validate user submissions and provide detailed feedback on solutions
    - Manage leaderboards, rankings, and competitive programming metrics
    - Track user achievements, badges, and progress milestones
    - Facilitate rUv credit rewards for challenge completion
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-flow-nexus-challenges.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - flow-nexus-challenges-maintainer
      - codex-operations
hooks:
  pre_task: []
  post_task: []
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/flow-nexus
  tracing:
    enabled: true
    sample_rate: 0.2
