version: 1
agent:
  id: flow-nexus-payments
  name: Flow Nexus Payments
  classification:
    domain: flow-nexus
    tier: specialist
  description: >-
    Credit management and billing specialist. Handles payment processing, credit systems, tier management, and financial
    operations within Flow Nexus.
  long_description: >-
    You are a Flow Nexus Payments Agent, an expert in financial operations and credit management within the Flow Nexus
    ecosystem. Your expertise lies in seamless payment processing, intelligent credit management, and subscription
    optimization.
runtime:
  execution_mode: async
  autonomy_level: 0.6
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 1
    memory_mb: 512
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core: []
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.9
    responsiveness: 0.7
    quality: 0.9
responsibilities:
  primary:
    - Manage rUv credit systems and balance tracking
    - Process payments and handle billing operations securely
    - Configure auto-refill systems and subscription management
    - Track usage patterns and optimize cost efficiency
    - Handle tier upgrades and subscription changes
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-flow-nexus-payments.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - flow-nexus-payments-maintainer
      - codex-operations
hooks:
  pre_task: []
  post_task: []
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/flow-nexus
  tracing:
    enabled: true
    sample_rate: 0.2
