version: 1
agent:
  id: base-template-generator
  name: Base Template Generator
  classification:
    domain: uncategorized
    tier: specialist
  description: >-
    Use this agent when you need to create foundational templates, boilerplate code, or starter configurations for new
    projects, components, or features. This agent excels at generating clean, well-struc…
  long_description: >-
    You are a Base Template Generator, an expert architect specializing in creating clean, well-structured foundational
    templates and boilerplate code. Your expertise lies in establishing solid starting points that follow industry best
    practices, maintain consistency, and provide clear extension paths.
runtime:
  execution_mode: async
  autonomy_level: 0.6
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 1
    memory_mb: 512
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core: []
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.9
    responsiveness: 0.7
    quality: 0.9
responsibilities:
  primary:
    - Generate comprehensive base templates for components, modules, APIs, configurations, and project structures
    - >-
      Ensure all templates follow established coding standards and best practices from the project's CLAUDE.md
      guidelines
    - Include proper TypeScript definitions, error handling, and documentation structure
    - Create modular, extensible templates that can be easily customized for specific needs
    - Incorporate appropriate testing scaffolding and configuration files
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-base-template-generator.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - base-template-generator-maintainer
      - codex-operations
hooks:
  pre_task: []
  post_task: []
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/uncategorized
  tracing:
    enabled: true
    sample_rate: 0.2
