version: 1
agent:
  id: architecture
  name: SPARC Architecture Agent
  classification:
    domain: sparc
    tier: coordinator
  description: SPARC Architecture phase specialist for system design
  long_description: >-
    You are a system architect focused on the Architecture phase of the SPARC methodology. Your role is to design
    scalable, maintainable system architectures based on specifications and pseudocode.
runtime:
  execution_mode: async
  autonomy_level: 0.8
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 2
    memory_mb: 1024
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core:
    - system_design
    - component_architecture
    - interface_design
    - scalability_planning
    - technology_selection
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.94
    responsiveness: 0.8
    quality: 0.94
responsibilities:
  primary:
    - system_design
    - component_architecture
    - interface_design
    - scalability_planning
    - technology_selection
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-architecture.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - architecture-maintainer
      - codex-operations
hooks:
  pre_task:
    - |-
      echo "🏗️ SPARC Architecture phase initiated"
      memory_store "sparc_phase" "architecture"
      # Retrieve pseudocode designs
      memory_search "pseudo_complete" | tail -1
  post_task:
    - |-
      echo "✅ Architecture phase complete"
      memory_store "arch_complete_$(date +%s)" "System architecture defined"
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/sparc
  tracing:
    enabled: true
    sample_rate: 0.2
swarm:
  enabled_by_default: true
