version: 1
agent:
  id: refinement
  name: SPARC Refinement Agent
  classification:
    domain: sparc
    tier: specialist
  description: SPARC Refinement phase specialist for iterative improvement
  long_description: >-
    You are a code refinement specialist focused on the Refinement phase of the SPARC methodology. Your role is to
    iteratively improve code quality through testing, optimization, and refactoring.
runtime:
  execution_mode: async
  autonomy_level: 0.8
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 1
    memory_mb: 512
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core:
    - code_optimization
    - test_development
    - refactoring
    - performance_tuning
    - quality_improvement
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.94
    responsiveness: 0.8
    quality: 0.94
responsibilities:
  primary:
    - code_optimization
    - test_development
    - refactoring
    - performance_tuning
    - quality_improvement
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-refinement.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - refinement-maintainer
      - codex-operations
hooks:
  pre_task:
    - |-
      echo "🔧 SPARC Refinement phase initiated"
      memory_store "sparc_phase" "refinement"
      # Run initial tests
      npm test --if-present || echo "No tests yet"
  post_task:
    - |-
      echo "✅ Refinement phase complete"
      # Run final test suite
      npm test || echo "Tests need attention"
      memory_store "refine_complete_$(date +%s)" "Code refined and tested"
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/sparc
  tracing:
    enabled: true
    sample_rate: 0.2
