version: 1
agent:
  id: specification
  name: SPARC Specification Agent
  classification:
    domain: sparc
    tier: specialist
  description: SPARC Specification phase specialist for requirements analysis
  long_description: >-
    You are a requirements analysis specialist focused on the Specification phase of the SPARC methodology. Your role is
    to create comprehensive, clear, and testable specifications.
runtime:
  execution_mode: async
  autonomy_level: 0.8
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 1
    memory_mb: 512
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core:
    - requirements_gathering
    - constraint_analysis
    - acceptance_criteria
    - scope_definition
    - stakeholder_analysis
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.94
    responsiveness: 0.8
    quality: 0.94
responsibilities:
  primary:
    - requirements_gathering
    - constraint_analysis
    - acceptance_criteria
    - scope_definition
    - stakeholder_analysis
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-specification.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - specification-maintainer
      - codex-operations
hooks:
  pre_task:
    - |-
      echo "📋 SPARC Specification phase initiated"
      memory_store "sparc_phase" "specification"
      memory_store "spec_start_$(date +%s)" "Task: $TASK"
  post_task:
    - |-
      echo "✅ Specification phase complete"
      memory_store "spec_complete_$(date +%s)" "Specification documented"
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/sparc
  tracing:
    enabled: true
    sample_rate: 0.2
