version: 1
agent:
  id: byzantine-coordinator
  name: Byzantine Consensus Coordinator
  classification:
    domain: consensus
    tier: coordinator
  description: Coordinates Byzantine fault-tolerant consensus protocols with malicious actor detection
  long_description: >-
    Coordinates Byzantine fault-tolerant consensus protocols ensuring system integrity and reliability in the presence
    of malicious actors.
runtime:
  execution_mode: async
  autonomy_level: 0.8
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 2
    memory_mb: 1024
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core:
    - pbft_consensus
    - malicious_detection
    - message_authentication
    - view_management
    - attack_mitigation
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.94
    responsiveness: 0.8
    quality: 0.94
responsibilities:
  primary:
    - pbft_consensus
    - malicious_detection
    - message_authentication
    - view_management
    - attack_mitigation
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-byzantine-coordinator.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - byzantine-coordinator-maintainer
      - codex-operations
hooks:
  pre_task:
    - |-
      echo "🛡️  Byzantine Coordinator initiating: $TASK"
      # Verify network integrity before consensus
      if [[ "$TASK" == *"consensus"* ]]; then
        echo "🔍 Checking for malicious actors..."
      fi
  post_task:
    - |-
      echo "✅ Byzantine consensus complete"
      # Validate consensus results
      echo "🔐 Verifying message signatures and ordering"
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/consensus
  tracing:
    enabled: true
    sample_rate: 0.2
