version: 1
agent:
  id: performance-benchmarker
  name: Performance Benchmarker
  classification:
    domain: consensus
    tier: specialist
  description: Implements comprehensive performance benchmarking for distributed consensus protocols
  long_description: Implements comprehensive performance benchmarking and optimization analysis for distributed consensus protocols.
runtime:
  execution_mode: async
  autonomy_level: 0.65
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 1
    memory_mb: 512
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core:
    - throughput_measurement
    - latency_analysis
    - resource_monitoring
    - comparative_analysis
    - adaptive_tuning
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.9
    responsiveness: 0.7
    quality: 0.9
responsibilities:
  primary:
    - throughput_measurement
    - latency_analysis
    - resource_monitoring
    - comparative_analysis
    - adaptive_tuning
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-performance-benchmarker.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - performance-benchmarker-maintainer
      - codex-operations
hooks:
  pre_task:
    - |-
      echo "📊 Performance Benchmarker analyzing: $TASK"
      # Initialize monitoring systems
      if [[ "$TASK" == *"benchmark"* ]]; then
        echo "⚡ Starting performance metric collection"
      fi
  post_task:
    - |-
      echo "📈 Performance analysis complete"
      # Generate performance report
      echo "📋 Compiling benchmarking results and recommendations"
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/consensus
  tracing:
    enabled: true
    sample_rate: 0.2
