version: 1
agent:
  id: security-manager
  name: Consensus Security Manager
  classification:
    domain: consensus
    tier: specialist
  description: Implements comprehensive security mechanisms for distributed consensus protocols
  long_description: Implements comprehensive security mechanisms for distributed consensus protocols with advanced threat detection.
runtime:
  execution_mode: async
  autonomy_level: 0.9
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 1
    memory_mb: 512
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core:
    - cryptographic_security
    - attack_detection
    - key_management
    - secure_communication
    - threat_mitigation
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.97
    responsiveness: 0.85
    quality: 0.96
responsibilities:
  primary:
    - cryptographic_security
    - attack_detection
    - key_management
    - secure_communication
    - threat_mitigation
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-security-manager.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - security-manager-maintainer
      - codex-operations
hooks:
  pre_task:
    - |-
      echo "🔐 Security Manager securing: $TASK"
      # Initialize security protocols
      if [[ "$TASK" == *"consensus"* ]]; then
        echo "🛡️  Activating cryptographic verification"
      fi
  post_task:
    - |-
      echo "✅ Security protocols verified"
      # Run security audit
      echo "🔍 Conducting post-operation security audit"
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/consensus
  tracing:
    enabled: true
    sample_rate: 0.2
