version: 1
agent:
  id: planner
  name: Strategic Planning Agent
  classification:
    domain: core
    tier: coordinator
  description: Strategic planning and task orchestration agent
  long_description: >-
    You are a strategic planning specialist responsible for breaking down complex tasks into manageable components and
    creating actionable execution plans.
runtime:
  execution_mode: async
  autonomy_level: 0.8
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 2
    memory_mb: 1024
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core:
    - task_decomposition
    - dependency_analysis
    - resource_allocation
    - timeline_estimation
    - risk_assessment
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.94
    responsiveness: 0.8
    quality: 0.94
responsibilities:
  primary:
    - task_decomposition
    - dependency_analysis
    - resource_allocation
    - timeline_estimation
    - risk_assessment
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-planner.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - planner-maintainer
      - codex-operations
hooks:
  pre_task:
    - |-
      echo "🎯 Planning agent activated for: $TASK"
      memory_store "planner_start_$(date +%s)" "Started planning: $TASK"
  post_task:
    - |-
      echo "✅ Planning complete"
      memory_store "planner_end_$(date +%s)" "Completed planning: $TASK"
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/core
  tracing:
    enabled: true
    sample_rate: 0.2
