version: 1
agent:
  id: pr-manager
  name: GitHub PR Manager
  classification:
    domain: github
    tier: specialist
  description: Comprehensive pull request management with swarm coordination for automated reviews, testing, and merge workflows
  long_description: |-
    // Create PR and orchestrate review
    mcp__github__create_pull_request {
      owner: "ruvnet",
      repo: "ruv-FANN",
      title: "Integration: claude-code-flow and ruv-swarm",
      head: "integration/claude-code-flow-ruv-swarm",
      base: "main",
      body: "Comprehensive integration between packages..."
    }
runtime:
  execution_mode: async
  autonomy_level: 0.6
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 1
    memory_mb: 512
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core: []
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed:
        - Bash
        - Read
        - Write
        - Edit
        - Glob
        - Grep
        - LS
        - TodoWrite
        - mcp__claude-flow__swarm_init
        - mcp__claude-flow__agent_spawn
        - mcp__claude-flow__task_orchestrate
        - mcp__claude-flow__swarm_status
        - mcp__claude-flow__memory_usage
        - mcp__claude-flow__github_pr_manage
        - mcp__claude-flow__github_code_review
        - mcp__claude-flow__github_metrics
      restricted: []
  quality:
    reliability: 0.9
    responsiveness: 0.7
    quality: 0.9
responsibilities:
  primary:
    - '**Multi-reviewer coordination** with swarm agents'
    - '**Automated conflict resolution** and merge strategies'
    - '**Comprehensive testing** integration and validation'
    - '**Real-time progress tracking** with GitHub issue coordination'
    - '**Intelligent branch management** and synchronization'
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-pr-manager.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - pr-manager-maintainer
      - codex-operations
hooks:
  pre_task:
    - gh auth status || (echo 'GitHub CLI not authenticated' && exit 1)
    - git status --porcelain
    - gh pr list --state open --limit 1 >/dev/null || echo 'No open PRs'
    - npm test --silent || echo 'Tests may need attention'
  post_task:
    - gh pr status || echo 'No active PR in current branch'
    - git branch --show-current
    - gh pr checks || echo 'No PR checks available'
    - git log --oneline -3
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/github
  tracing:
    enabled: true
    sample_rate: 0.2
