version: 1
agent:
  id: task-orchestrator
  name: Task Orchestrator Agent
  classification:
    domain: templates
    tier: coordinator
  description: Central coordination agent for task decomposition, execution planning, and result synthesis
  long_description: ''
runtime:
  execution_mode: async
  autonomy_level: 0.8
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 2
    memory_mb: 1024
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core:
    - task_decomposition
    - execution_planning
    - dependency_management
    - result_aggregation
    - progress_tracking
    - priority_management
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.94
    responsiveness: 0.8
    quality: 0.94
responsibilities:
  primary:
    - task_decomposition
    - execution_planning
    - dependency_management
    - result_aggregation
    - progress_tracking
    - priority_management
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-task-orchestrator.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - task-orchestrator-maintainer
      - codex-operations
hooks:
  pre_task:
    - |-
      echo "🎯 Task Orchestrator initializing"
      memory_store "orchestrator_start" "$(date +%s)"
      # Check for existing task plans
      memory_search "task_plan" | tail -1
  post_task:
    - |-
      echo "✅ Task orchestration complete"
      memory_store "orchestration_complete_$(date +%s)" "Tasks distributed and monitored"
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/templates
  tracing:
    enabled: true
    sample_rate: 0.2
