version: 1
agent:
  id: code-analyzer
  name: Code Analyzer Agent
  classification:
    domain: analysis
    tier: specialist
  description: Advanced code quality analysis agent for comprehensive code reviews and improvements
  long_description: >-
    An advanced code quality analysis specialist that performs comprehensive code reviews, identifies improvements, and
    ensures best practices are followed throughout the codebase.
runtime:
  execution_mode: async
  autonomy_level: 0.8
  concurrency:
    max_parallel_tasks: 3
    queue_strategy: priority
  resource_limits:
    cpu: 1
    memory_mb: 512
    disk_mb: 1024
  heartbeat_interval_ms: 15000
  timeout_ms: 600000
capabilities:
  core: []
  detail:
    languages: []
    frameworks: []
    domains: []
    tools:
      allowed: []
      restricted: []
  quality:
    reliability: 0.94
    responsiveness: 0.8
    quality: 0.94
responsibilities:
  primary:
    - Analyze code structure and organization
    - Evaluate naming conventions and consistency
    - Check for proper error handling
    - Assess code readability and maintainability
    - Review documentation completeness
  secondary: []
triggers:
  keywords: []
  regex: []
  file_patterns: []
  delegations:
    prefers: []
    complements: []
workflow:
  startup_script: scripts/start-code-analyzer.ts
  setup_tasks: []
  teardown_tasks: []
  dependencies:
    runtime: []
    packages: []
memory:
  retention:
    short_term: 7d
    long_term: true
  namespaces: []
  sharing_policy:
    share_with: []
    redact: []
metrics:
  tracked:
    - tasks_completed
    - avg_latency_ms
    - success_rate
  thresholds:
    heartbeat_miss: 2
    failure_rate_pct: 10
  escalation:
    notify:
      - code-analyzer-maintainer
      - codex-operations
hooks:
  pre_task:
    - >-
      npx claude-flow@alpha hooks pre-task --description "Code analysis agent starting: ${description}"
      --auto-spawn-agents false
  post_task:
    - npx claude-flow@alpha hooks post-task --task-id "analysis-${timestamp}" --analyze-performance true
  failure: []
testing:
  verification_policy: require-smoke-on-spawn
observability:
  log_level: info
  log_channels:
    - codex://logs/analysis
  tracing:
    enabled: true
    sample_rate: 0.2
